version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_dev
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shoe_go_next

  shoe-go:
    build:
      context: ./
      dockerfile: Dockerfile.air
    container_name: shoeGo
    env_file: ./.env.docker
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - shoe_go_next

volumes:
  postgres_data:

networks:
  shoe_go_next:
    external: true
      