name: IBM cloud code engine deployment
on:
  push:
    branches:
    - master

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f container-registry
   
    - name: Login to IBM Cloud Private Registry
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g default
        ibmcloud cr login
      env:
        IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        CR_REGION: ca-tor
        CR_NAMESPACE: ns_1

    - name: Get Commit SHA
      id: get_sha
      run: echo "::set-output name=SHA::$(git rev-parse --short ${{ github.sha }})"

    - name: Build and push Docker image
      run: |
        DOCKER_IMAGE_TAG=ca.icr.io/${CR_NAMESPACE}/<YOUR_DOCKER_IMAGE>:${{ steps.get_sha.outputs.SHA }}
        docker build -t $DOCKER_IMAGE_TAG .
        docker push $DOCKER_IMAGE_TAG
      env:
        CR_NAMESPACE: ns_1
        DOCKER_IMAGE: shoego

    
  
  
    
