name: IBM cloud code engine deployment
on:
  push:
    branches:
    - master

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Set up the IBM Cloud CLI
      # You may pin to the exact commit or the version.
      # uses: dprosper/ic-setup-cli@5a5c220653d4dae444e2ea31242bb065fd48fd5d
      uses: dprosper/ic-setup-cli@v0.1.2
      with:
        # IBM Cloud API key
        API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        # IBM Cloud Region
        REGION: ca-tor
        # IBM Cloud resource group
      # optional, default is default
        # List of plugins to install and separated by a comma to get a full list of available 
    # Visit the Reference section on the https://cloud.ibm.com/docs/cli documentation page.
        INSTALL_PLUGINS: container-registry

    - name: Login to IBM Cloud Private Registry
      run: |
        ibmcloud cr login
        ibmcloud cr namespace-add <YOUR_NAMESPACE>
      env:
        IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        CR_REGION: ca-tor
        CR_NAMESPACE: ns_1

    - name: Get Commit SHA
      id: get_sha
      run: echo "::set-output name=SHA::$(git rev-parse --short ${{ github.sha }})"

    - name: Build and push Docker image
      run: |
        DOCKER_IMAGE_TAG=ca.icr.io/${CR_NAMESPACE}/<YOUR_DOCKER_IMAGE>:${{ steps.get_sha.outputs.SHA }}
        docker build -t $DOCKER_IMAGE_TAG .
        docker push $DOCKER_IMAGE_TAG
      env:
        CR_NAMESPACE: ns_1
        DOCKER_IMAGE: shoego

    
  
  
    
